# Generated by Django 2.0.9 on 2018-11-30 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomments',
            name='eventId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
    ]
